// Pre-determined recipes library (20+ recipes)
// Organized by cuisine type and dietary restrictions

export interface Recipe {
    id: string;
    title: string;
    cuisine: string;
    dietaryTags: string[];
    time: string;
    servings: number;
    difficulty: 'Easy' | 'Medium' | 'Hard';
    ingredients: string[];
    instructions: string[];
    tips: string;
    calories: number;
    protein?: number;
    carbs?: number;
    fat?: number;
}

export const PREDEFINED_RECIPES: Recipe[] = [
    // === ITALIAN ===
    {
        id: 'italian-1',
        title: 'Classic Spaghetti Carbonara',
        cuisine: 'Italian',
        dietaryTags: ['high-protein'],
        time: '25 mins',
        servings: 4,
        difficulty: 'Medium',
        ingredients: [
            '400g spaghetti',
            '200g pancetta or guanciale',
            '4 large eggs',
            '100g Pecorino Romano cheese',
            '50g Parmesan cheese',
            'Black pepper',
            'Salt',
        ],
        instructions: [
            'Bring a large pot of salted water to boil and cook spaghetti according to package directions.',
            'While pasta cooks, cut pancetta into small cubes and fry in a pan until crispy (5-7 mins).',
            'In a bowl, whisk eggs with grated Pecorino and Parmesan. Add plenty of black pepper.',
            'Drain pasta, reserving 1 cup of pasta water.',
            'Remove pan from heat. Add hot pasta to pancetta, then quickly stir in egg mixture.',
            'Toss vigorously - the residual heat will cook the eggs into a creamy sauce.',
            'Add pasta water if needed for consistency. Serve immediately with extra cheese.',
        ],
        tips: 'Never add the egg mixture while the pan is on heat - this will scramble the eggs! Work quickly off the heat.',
        calories: 650,
        protein: 28,
        carbs: 72,
        fat: 26,
    },
    {
        id: 'italian-2',
        title: 'Margherita Pizza',
        cuisine: 'Italian',
        dietaryTags: ['vegetarian'],
        time: '45 mins',
        servings: 2,
        difficulty: 'Medium',
        ingredients: [
            '500g pizza dough',
            '400g San Marzano tomatoes',
            '250g fresh mozzarella',
            'Fresh basil leaves',
            'Extra virgin olive oil',
            'Salt',
            'Garlic (optional)',
        ],
        instructions: [
            'Preheat oven to maximum temperature (250°C/480°F) with pizza stone if available.',
            'Blend tomatoes with salt and a garlic clove for 30 seconds.',
            'Stretch dough on floured surface into 12-inch rounds.',
            'Spread thin layer of tomato sauce, leaving 2-inch border.',
            'Tear mozzarella into pieces and distribute evenly.',
            'Bake for 10-12 minutes until crust is golden and cheese bubbles.',
            'Top with fresh basil and drizzle with olive oil.',
        ],
        tips: 'Less is more with sauce - too much makes the pizza soggy. Fresh mozzarella should be drained first.',
        calories: 580,
        protein: 24,
        carbs: 68,
        fat: 22,
    },
    {
        id: 'italian-3',
        title: 'Risotto Milanese',
        cuisine: 'Italian',
        dietaryTags: ['gluten-free', 'vegetarian'],
        time: '40 mins',
        servings: 4,
        difficulty: 'Hard',
        ingredients: [
            '320g Arborio rice',
            '1.5L vegetable or chicken stock',
            '1 small onion',
            '100ml white wine',
            '80g butter',
            '80g Parmesan cheese',
            'Saffron threads',
            'Salt and pepper',
        ],
        instructions: [
            'Heat stock in a separate pot and keep simmering.',
            'Sauté finely chopped onion in half the butter until translucent.',
            'Add rice and toast for 2 minutes, stirring constantly.',
            'Pour in wine and stir until absorbed.',
            'Add saffron to a ladle of hot stock, then add to rice.',
            'Add stock one ladle at a time, stirring constantly until absorbed.',
            'Continue for 18-20 minutes until rice is creamy but al dente.',
            'Remove from heat, stir in remaining butter and Parmesan.',
            'Cover and rest 2 minutes before serving.',
        ],
        tips: 'Constant stirring releases the starch for creaminess. The rice should ripple when you shake the pan.',
        calories: 520,
        protein: 14,
        carbs: 65,
        fat: 22,
    },
    // === CHINESE ===
    {
        id: 'chinese-1',
        title: 'Kung Pao Chicken',
        cuisine: 'Chinese',
        dietaryTags: ['high-protein', 'low-carb'],
        time: '30 mins',
        servings: 4,
        difficulty: 'Medium',
        ingredients: [
            '500g chicken breast, cubed',
            '100g roasted peanuts',
            '8 dried red chilies',
            '4 cloves garlic, sliced',
            '1 inch ginger, minced',
            '2 tbsp soy sauce',
            '1 tbsp black vinegar',
            '1 tsp sugar',
            '1 tsp cornstarch',
            '2 tbsp Shaoxing wine',
            'Sichuan peppercorns',
            'Spring onions',
        ],
        instructions: [
            'Marinate chicken with soy sauce, wine, and cornstarch for 15 minutes.',
            'Make sauce: mix vinegar, sugar, soy sauce, and a splash of water.',
            'Heat oil in wok over high heat. Stir-fry chicken until golden, remove.',
            'In same wok, fry chilies and peppercorns until fragrant.',
            'Add garlic, ginger, and peanuts. Stir-fry 30 seconds.',
            'Return chicken, add sauce, toss to coat.',
            'Garnish with spring onions and serve immediately.',
        ],
        tips: 'Have all ingredients prepped before starting - this dish cooks very quickly! Adjust chilies to your heat preference.',
        calories: 420,
        protein: 35,
        carbs: 12,
        fat: 24,
    },
    {
        id: 'chinese-2',
        title: 'Mapo Tofu',
        cuisine: 'Chinese',
        dietaryTags: ['vegetarian', 'high-protein'],
        time: '25 mins',
        servings: 4,
        difficulty: 'Easy',
        ingredients: [
            '400g silken tofu, cubed',
            '200g ground pork or mushroom (vegan)',
            '3 tbsp doubanjiang (chili bean paste)',
            '2 tbsp fermented black beans',
            '4 cloves garlic, minced',
            '1 inch ginger, minced',
            '1 cup chicken or vegetable stock',
            '2 tbsp soy sauce',
            '1 tsp sugar',
            'Cornstarch slurry',
            'Sichuan peppercorn powder',
            'Spring onions',
        ],
        instructions: [
            'Blanch tofu in hot water for 2 minutes, drain.',
            'Sauté ground meat until browned (or mushrooms until golden).',
            'Add doubanjiang and black beans, fry until fragrant and oily.',
            'Add garlic, ginger, stock, soy sauce, and sugar.',
            'Gently add tofu, simmer 5 minutes.',
            'Thicken with cornstarch slurry.',
            'Serve over rice with Sichuan peppercorn powder and spring onions.',
        ],
        tips: 'Handle tofu gently to keep cubes intact. The dish should be very spicy and numbing.',
        calories: 280,
        protein: 18,
        carbs: 14,
        fat: 18,
    },
    {
        id: 'chinese-3',
        title: 'Sweet and Sour Pork',
        cuisine: 'Chinese',
        dietaryTags: [],
        time: '35 mins',
        servings: 4,
        difficulty: 'Medium',
        ingredients: [
            '500g pork shoulder, cubed',
            '1 bell pepper, chunked',
            '1 onion, chunked',
            '1 cup pineapple chunks',
            '3 tbsp ketchup',
            '3 tbsp rice vinegar',
            '2 tbsp sugar',
            '1 tbsp soy sauce',
            'Cornstarch for coating',
            'Egg for batter',
            'Oil for frying',
        ],
        instructions: [
            'Coat pork in cornstarch, then egg, then cornstarch again.',
            'Deep fry pork at 180°C until golden and crispy. Drain.',
            'Make sauce: ketchup, vinegar, sugar, soy sauce, and 100ml water.',
            'Stir-fry vegetables for 2 minutes.',
            'Add sauce to pan, bring to simmer.',
            'Thicken with cornstarch slurry.',
            'Add fried pork and pineapple, toss to coat.',
            'Serve immediately with rice.',
        ],
        tips: 'Double-fry the pork for extra crispiness. The sauce should be glossy and coat the back of a spoon.',
        calories: 580,
        protein: 28,
        carbs: 48,
        fat: 28,
    },
    // === AMERICAN ===
    {
        id: 'american-1',
        title: 'Classic Cheeseburger',
        cuisine: 'American',
        dietaryTags: ['high-protein', 'low-carb'],
        time: '20 mins',
        servings: 4,
        difficulty: 'Easy',
        ingredients: [
            '600g ground beef (80/20)',
            '4 cheese slices (Cheddar/American)',
            '4 burger buns',
            'Lettuce leaves',
            'Tomato slices',
            'Pickles',
            'Red onion',
            'Salt and pepper',
            'Burger sauce',
        ],
        instructions: [
            'Divide beef into 4 portions, form into patties slightly wider than buns.',
            'Make a thumb indent in center of each patty to prevent bulging.',
            'Season generously with salt and pepper.',
            'Heat grill or pan to high heat.',
            'Cook patties 3-4 minutes per side for medium.',
            'Add cheese in last minute, cover to melt.',
            'Toast buns lightly.',
            'Assemble: bun bottom, sauce, lettuce, patty, cheese, tomato, pickles, onion, bun top.',
        ],
        tips: 'Don\'t press down on patties while cooking - you\'ll lose the juices! Let meat rest at room temp 15 mins before cooking.',
        calories: 720,
        protein: 42,
        carbs: 38,
        fat: 42,
    },
    {
        id: 'american-2',
        title: 'Chicken Fried Rice',
        cuisine: 'American-Asian',
        dietaryTags: ['high-protein'],
        time: '25 mins',
        servings: 4,
        difficulty: 'Easy',
        ingredients: [
            '400g cooked chicken, diced',
            '4 cups cooked rice (day-old, cold)',
            '3 eggs, beaten',
            '1 cup mixed vegetables (peas, carrots, corn)',
            '4 cloves garlic, minced',
            '3 tbsp soy sauce',
            '1 tbsp sesame oil',
            '2 spring onions',
            'Oil for frying',
        ],
        instructions: [
            'Heat oil in wok over high heat.',
            'Scramble eggs, remove and set aside.',
            'Add more oil, stir-fry chicken until heated through.',
            'Add garlic and vegetables, stir-fry 2 minutes.',
            'Add cold rice, break up clumps, stir-fry 3 minutes.',
            'Add soy sauce, sesame oil, and eggs.',
            'Toss everything together, garnish with spring onions.',
        ],
        tips: 'Day-old cold rice is essential - fresh rice gets mushy. Keep heat high for that wok flavor.',
        calories: 480,
        protein: 28,
        carbs: 52,
        fat: 18,
    },
    {
        id: 'american-3',
        title: 'BBQ Pulled Pork Sandwich',
        cuisine: 'American',
        dietaryTags: ['high-protein'],
        time: '4 hours',
        servings: 8,
        difficulty: 'Medium',
        ingredients: [
            '1.5kg pork shoulder',
            '2 tbsp brown sugar',
            '2 tbsp paprika',
            '1 tbsp garlic powder',
            '1 tbsp onion powder',
            '1 tsp cayenne',
            'Salt and pepper',
            '500ml BBQ sauce',
            '8 burger buns',
            'Coleslaw',
        ],
        instructions: [
            'Mix brown sugar, paprika, garlic powder, onion powder, cayenne, salt, and pepper.',
            'Rub spice mix all over pork shoulder.',
            'Slow cook at 150°C for 4-5 hours until meat pulls apart easily.',
            'Remove pork, let rest 15 minutes.',
            'Shred with two forks, discarding fat.',
            'Mix shredded pork with half the BBQ sauce.',
            'Serve on toasted buns with coleslaw and extra sauce.',
        ],
        tips: 'The meat is ready when a fork twists easily. Save the cooking juices to mix with the pork for extra moisture.',
        calories: 680,
        protein: 45,
        carbs: 52,
        fat: 32,
    },
    // === MEXICAN ===
    {
        id: 'mexican-1',
        title: 'Chicken Tacos al Pastor',
        cuisine: 'Mexican',
        dietaryTags: ['high-protein', 'low-carb'],
        time: '30 mins',
        servings: 4,
        difficulty: 'Medium',
        ingredients: [
            '500g chicken thighs, sliced',
            '2 tbsp achiote paste',
            '2 tbsp lime juice',
            '1 tsp cumin',
            '1 tsp dried oregano',
            '8 corn tortillas',
            '1 white onion, diced',
            'Fresh cilantro',
            'Salsa verde',
            'Pineapple chunks',
            'Lime wedges',
        ],
        instructions: [
            'Marinate chicken with achiote, lime juice, cumin, oregano, salt for 20 mins.',
            'Heat a skillet over high heat.',
            'Cook chicken 5-6 minutes until charred and cooked through.',
            'Warm tortillas in a dry pan.',
            'Assemble tacos: tortilla, chicken, pineapple, onion, cilantro.',
            'Top with salsa verde and lime juice.',
        ],
        tips: 'Don\'t skip the pineapple - it\'s essential for authentic Pastor flavor. Char the tortillas for best taste.',
        calories: 380,
        protein: 32,
        carbs: 28,
        fat: 16,
    },
    {
        id: 'mexican-2',
        title: 'Beef Burrito Bowl',
        cuisine: 'Mexican',
        dietaryTags: ['low-carb', 'high-protein', 'gluten-free'],
        time: '25 mins',
        servings: 4,
        difficulty: 'Easy',
        ingredients: [
            '500g ground beef',
            '2 tbsp taco seasoning',
            '2 cups cauliflower rice',
            '1 cup black beans',
            '1 cup corn',
            '1 avocado, sliced',
            '1 cup shredded cheese',
            'Sour cream',
            'Salsa',
            'Lime',
            'Cilantro',
        ],
        instructions: [
            'Brown ground beef in a skillet, drain excess fat.',
            'Add taco seasoning and 100ml water, simmer 5 minutes.',
            'Sauté cauliflower rice with a pinch of salt for 5 minutes.',
            'Warm black beans and corn together.',
            'Assemble bowls: cauliflower rice base, beef, beans, corn.',
            'Top with avocado, cheese, sour cream, salsa, cilantro.',
            'Serve with lime wedges.',
        ],
        tips: 'Make your own taco seasoning: 1 tbsp cumin, 1 tbsp chili powder, 1 tsp garlic powder, 1 tsp onion powder, 1 tsp paprika.',
        calories: 520,
        protein: 38,
        carbs: 22,
        fat: 32,
    },
    {
        id: 'mexican-3',
        title: 'Vegetarian Enchiladas',
        cuisine: 'Mexican',
        dietaryTags: ['vegetarian', 'high-protein'],
        time: '45 mins',
        servings: 6,
        difficulty: 'Medium',
        ingredients: [
            '12 corn tortillas',
            '2 cups black beans',
            '2 cups shredded cheese',
            '1 cup sour cream',
            '2 cups enchilada sauce',
            '1 onion, diced',
            '1 bell pepper, diced',
            '1 cup corn',
            'Cumin',
            'Chili powder',
        ],
        instructions: [
            'Preheat oven to 180°C.',
            'Sauté onion and pepper until soft.',
            'Mix beans, corn, half the cheese, sour cream, cumin, and chili powder.',
            'Warm tortillas to make them pliable.',
            'Fill each tortilla with bean mixture, roll up.',
            'Place in baking dish, cover with enchilada sauce.',
            'Top with remaining cheese.',
            'Bake 20 minutes until bubbly.',
            'Garnish with cilantro and serve.',
        ],
        tips: 'Warm tortillas in a hot pan for 10 seconds each to prevent cracking when rolling.',
        calories: 420,
        protein: 18,
        carbs: 48,
        fat: 20,
    },
    // === JAPANESE ===
    {
        id: 'japanese-1',
        title: 'Chicken Teriyaki',
        cuisine: 'Japanese',
        dietaryTags: ['high-protein', 'gluten-free'],
        time: '25 mins',
        servings: 4,
        difficulty: 'Easy',
        ingredients: [
            '600g chicken thighs',
            '4 tbsp soy sauce',
            '3 tbsp mirin',
            '2 tbsp sake',
            '2 tbsp sugar',
            '1 tbsp ginger, grated',
            '2 cloves garlic, minced',
            'Sesame seeds',
            'Spring onions',
            'Steamed rice',
        ],
        instructions: [
            'Score chicken thighs in a crosshatch pattern.',
            'Mix soy sauce, mirin, sake, sugar, ginger, and garlic for sauce.',
            'Pan-fry chicken skin-side down until crispy (6-7 mins).',
            'Flip chicken, cook another 5 minutes.',
            'Add sauce, simmer until thick and glossy.',
            'Remove chicken, reduce sauce if needed.',
            'Slice chicken, serve with rice, sauce, sesame seeds, and spring onions.',
        ],
        tips: 'Start skin-side down for crispy skin. Don\'t move the chicken until it releases naturally from the pan.',
        calories: 420,
        protein: 35,
        carbs: 28,
        fat: 18,
    },
    {
        id: 'japanese-2',
        title: 'Ramen Bowl',
        cuisine: 'Japanese',
        dietaryTags: ['high-protein'],
        time: '1 hour',
        servings: 4,
        difficulty: 'Hard',
        ingredients: [
            '4 packs ramen noodles',
            '1L chicken stock',
            '200ml miso paste',
            '4 soft-boiled eggs',
            '400g chicken breast',
            '200g bamboo shoots',
            'Spring onions',
            'Nori sheets',
            'Sesame oil',
            'Garlic',
            'Ginger',
        ],
        instructions: [
            'Season and grill chicken, slice thinly.',
            'Boil eggs for 6.5 minutes, ice bath, peel, marinate in soy sauce.',
            'Simmer stock with garlic, ginger, sesame oil for 20 minutes.',
            'Whisk in miso paste (don\'t boil after adding miso).',
            'Cook ramen noodles according to package.',
            'Assemble: noodles in bowl, hot broth, chicken, egg, bamboo shoots.',
            'Garnish with spring onions and nori.',
        ],
        tips: 'Keep broth at a simmer after adding miso - boiling makes it bitter. Perfect soft egg: 6.5 minutes in boiling water.',
        calories: 580,
        protein: 32,
        carbs: 62,
        fat: 22,
    },
    {
        id: 'japanese-3',
        title: 'Vegetable Tempura',
        cuisine: 'Japanese',
        dietaryTags: ['vegetarian'],
        time: '30 mins',
        servings: 4,
        difficulty: 'Medium',
        ingredients: [
            '200g all-purpose flour',
            '1 egg yolk',
            '300ml ice-cold sparkling water',
            'Sweet potato, sliced',
            'Eggplant, sliced',
            'Bell peppers',
            'Broccoli florets',
            'Shrimp (optional)',
            'Oil for frying',
            'Tentsuyu dipping sauce',
        ],
        instructions: [
            'Keep flour, egg yolk, and water ice-cold before mixing.',
            'Mix batter with chopsticks - it should be lumpy!',
            'Heat oil to 170-180°C.',
            'Dip vegetables in batter, let excess drip off.',
            'Fry until golden and crispy (2-3 minutes).',
            'Drain on wire rack, not paper.',
            'Serve immediately with tentsuyu dipping sauce.',
        ],
        tips: 'The batter must be cold and lumpy for crispy tempura. Fry in small batches to maintain oil temperature.',
        calories: 380,
        protein: 8,
        carbs: 52,
        fat: 16,
    },
    // === INDIAN ===
    {
        id: 'indian-1',
        title: 'Butter Chicken (Murgh Makhani)',
        cuisine: 'Indian',
        dietaryTags: ['high-protein', 'gluten-free'],
        time: '45 mins',
        servings: 4,
        difficulty: 'Medium',
        ingredients: [
            '600g chicken thighs, cubed',
            '200g yogurt',
            '2 tbsp garam masala',
            '1 tbsp ginger-garlic paste',
            '400g tomato puree',
            '100ml heavy cream',
            '50g butter',
            '1 onion, diced',
            '2 tbsp tomato paste',
            '1 tsp kasuri methi',
            'Salt',
        ],
        instructions: [
            'Marinate chicken in yogurt, half the garam masala, and ginger-garlic paste for 30 mins.',
            'Grill or pan-fry chicken until charred, set aside.',
            'Melt butter, sauté onion until golden.',
            'Add tomato paste, cook 2 minutes.',
            'Add tomato puree, remaining garam masala, simmer 10 minutes.',
            'Stir in cream and kasuri methi.',
            'Add chicken, simmer 5 minutes.',
            'Serve with naan or rice.',
        ],
        tips: 'Crush kasuri methi (dried fenugreek leaves) between your palms before adding. Don\'t overcook the chicken.',
        calories: 580,
        protein: 38,
        carbs: 18,
        fat: 42,
    },
    {
        id: 'indian-2',
        title: 'Chana Masala',
        cuisine: 'Indian',
        dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'high-protein'],
        time: '35 mins',
        servings: 4,
        difficulty: 'Easy',
        ingredients: [
            '800g chickpeas (2 cans)',
            '2 onions, diced',
            '4 tomatoes, chopped',
            '2 tbsp chana masala spice',
            '1 tsp turmeric',
            '1 tsp cumin seeds',
            'Ginger-garlic paste',
            'Fresh cilantro',
            'Lime juice',
            'Oil',
        ],
        instructions: [
            'Heat oil, add cumin seeds until they sputter.',
            'Sauté onions until deep golden brown.',
            'Add ginger-garlic paste, cook 1 minute.',
            'Add tomatoes, turmeric, chana masala, cook until oil separates.',
            'Add chickpeas with their liquid.',
            'Simmer 15 minutes, mash some chickpeas for thickness.',
            'Finish with lime juice and cilantro.',
            'Serve with rice or roti.',
        ],
        tips: 'Brown onions well for depth of flavor. Mash some chickpeas to naturally thicken the sauce.',
        calories: 380,
        protein: 18,
        carbs: 52,
        fat: 12,
    },
    {
        id: 'indian-3',
        title: 'Biryani',
        cuisine: 'Indian',
        dietaryTags: ['high-protein', 'gluten-free'],
        time: '1 hour',
        servings: 6,
        difficulty: 'Hard',
        ingredients: [
            '500g basmati rice',
            '600g chicken or lamb, cubed',
            '200g yogurt',
            '2 onions, thinly sliced',
            'Saffron strands',
            '4 tbsp ghee',
            'Whole spices (cardamom, cinnamon, cloves)',
            'Biryani masala',
            'Mint and cilantro',
            'Ginger-garlic paste',
        ],
        instructions: [
            'Marinate meat in yogurt, half the spices, ginger-garlic paste for 1 hour.',
            'Soak rice 30 minutes, drain.',
            'Fry onions until crispy, set aside half for garnish.',
            'Cook meat with fried onions, spices, masala until tender.',
            'Par-boil rice with whole spices until 70% cooked.',
            'Layer rice over meat, sprinkle saffron milk, ghee, herbs.',
            'Cover tightly, cook on low heat 25 minutes (dum method).',
            'Rest 10 minutes before opening and serving.',
        ],
        tips: 'The dum (steam cooking) is crucial. Seal the pot with dough if needed. Don\'t stir after layering.',
        calories: 620,
        protein: 32,
        carbs: 68,
        fat: 24,
    },
    // === THAI ===
    {
        id: 'thai-1',
        title: 'Pad Thai',
        cuisine: 'Thai',
        dietaryTags: ['high-protein'],
        time: '30 mins',
        servings: 4,
        difficulty: 'Medium',
        ingredients: [
            '300g rice noodles',
            '300g shrimp or chicken',
            '4 eggs',
            '100g bean sprouts',
            '50g roasted peanuts',
            '3 tbsp tamarind paste',
            '2 tbsp fish sauce',
            '2 tbsp sugar',
            'Dried chilies',
            'Garlic',
            'Spring onions',
            'Lime wedges',
        ],
        instructions: [
            'Soak rice noodles in warm water 30 minutes, drain.',
            'Mix tamarind, fish sauce, sugar for sauce.',
            'Heat oil, stir-fry protein until cooked.',
            'Push aside, scramble eggs in same pan.',
            'Add noodles and sauce, toss 2 minutes.',
            'Add bean sprouts, spring onions, toss briefly.',
            'Serve with crushed peanuts, lime, and dried chilies.',
        ],
        tips: 'Have everything ready before cooking - Pad Thai comes together fast. Noodles should be chewy, not mushy.',
        calories: 480,
        protein: 28,
        carbs: 58,
        fat: 18,
    },
    {
        id: 'thai-2',
        title: 'Green Curry',
        cuisine: 'Thai',
        dietaryTags: ['gluten-free', 'high-protein'],
        time: '35 mins',
        servings: 4,
        difficulty: 'Easy',
        ingredients: [
            '400ml coconut milk',
            '3 tbsp green curry paste',
            '500g chicken breast',
            '1 cup bamboo shoots',
            'Thai eggplant',
            'Thai basil',
            '2 tbsp fish sauce',
            '1 tbsp palm sugar',
            'Kaffir lime leaves',
            'Thai chilies',
        ],
        instructions: [
            'Heat thick coconut cream in pan until oil separates.',
            'Fry green curry paste until fragrant.',
            'Add sliced chicken, stir-fry until sealed.',
            'Add remaining coconut milk, bring to simmer.',
            'Add vegetables, cook 5 minutes.',
            'Season with fish sauce and palm sugar.',
            'Add lime leaves torn to release flavor.',
            'Garnish with Thai basil and chilies.',
        ],
        tips: 'Fry the curry paste in coconut cream first for maximum flavor. Don\'t boil vigorously or coconut milk will separate.',
        calories: 420,
        protein: 32,
        carbs: 12,
        fat: 30,
    },
    // === MEDITERRANEAN ===
    {
        id: 'med-1',
        title: 'Greek Salad with Grilled Chicken',
        cuisine: 'Mediterranean',
        dietaryTags: ['low-carb', 'high-protein', 'gluten-free'],
        time: '20 mins',
        servings: 4,
        difficulty: 'Easy',
        ingredients: [
            '500g chicken breast',
            '4 tomatoes, chunked',
            '1 cucumber, sliced',
            '1 red onion, sliced',
            '200g feta cheese',
            '100g kalamata olives',
            'Olive oil',
            'Oregano',
            'Lemon juice',
        ],
        instructions: [
            'Season chicken with oregano, salt, pepper.',
            'Grill chicken 6-7 minutes per side.',
            'Cut tomatoes into wedges, slice cucumber.',
            'Combine tomatoes, cucumber, onion, olives in bowl.',
            'Drizzle with olive oil and lemon juice.',
            'Top with whole feta block.',
            'Slice chicken, serve over salad.',
        ],
        tips: 'Use block feta, not crumbled - it\'s much tastier. Let salad sit 5 minutes for flavors to meld.',
        calories: 380,
        protein: 35,
        carbs: 12,
        fat: 24,
    },
    {
        id: 'med-2',
        title: 'Shakshuka',
        cuisine: 'Mediterranean',
        dietaryTags: ['vegetarian', 'gluten-free', 'low-carb'],
        time: '30 mins',
        servings: 4,
        difficulty: 'Easy',
        ingredients: [
            '8 eggs',
            '1 can crushed tomatoes',
            '1 onion, diced',
            '1 bell pepper, diced',
            '4 cloves garlic',
            '1 tsp cumin',
            '1 tsp paprika',
            'Feta cheese',
            'Fresh cilantro',
            'Olive oil',
        ],
        instructions: [
            'Sauté onion and pepper until soft.',
            'Add garlic, cumin, paprika, cook 1 minute.',
            'Add tomatoes, simmer 10 minutes.',
            'Make wells in sauce, crack eggs into them.',
            'Cover, cook until whites are set but yolks runny.',
            'Top with feta and cilantro.',
            'Serve immediately with bread.',
        ],
        tips: 'Don\' overcook the eggs - they should be runny for dipping bread. Perfect for breakfast or dinner.',
        calories: 280,
        protein: 16,
        carbs: 14,
        fat: 18,
    },
    // === KOREAN ===
    {
        id: 'korean-1',
        title: 'Bibimbap',
        cuisine: 'Korean',
        dietaryTags: ['high-protein', 'gluten-free'],
        time: '45 mins',
        servings: 4,
        difficulty: 'Medium',
        ingredients: [
            '4 cups steamed rice',
            '400g beef bulgogi',
            '4 eggs',
            'Spinach',
            'Bean sprouts',
            'Carrots, julienned',
            'Zucchini',
            'Mushrooms',
            'Gochujang (chili paste)',
            'Sesame oil',
        ],
        instructions: [
            'Blanch spinach with sesame oil and garlic.',
            'Blanch bean sprouts with salt.',
            'Stir-fry carrots, zucchini, mushrooms separately.',
            'Marinate and cook beef.',
            'Fry eggs sunny-side up.',
            'Arrange rice in bowls, top with vegetables and beef.',
            'Add egg on top, serve with gochujang.',
            'Mix everything before eating.',
        ],
        tips: 'Each vegetable should be seasoned separately. For crispy rice, serve in a hot stone pot (dolsot).',
        calories: 580,
        protein: 32,
        carbs: 68,
        fat: 22,
    },
];

// Look up a curated recipe by its stable id (e.g. "italian-1").
export function getRecipeById(id: string): Recipe | undefined {
    return PREDEFINED_RECIPES.find((r) => r.id === id);
}

// Dietary restriction presets
export const DIETARY_PRESETS = [
    { id: 'low-carb', name: 'Low-Carb', icon: '🥗' },
    { id: 'high-protein', name: 'High-Protein', icon: '💪' },
    { id: 'gluten-free', name: 'Gluten-Free', icon: '🌾' },
    { id: 'vegan', name: 'Vegan', icon: '🌱' },
    { id: 'vegetarian', name: 'Vegetarian', icon: '🥬' },
    { id: 'keto', name: 'Keto', icon: '🥑' },
    { id: 'dairy-free', name: 'Dairy-Free', icon: '🥛' },
    { id: 'paleo', name: 'Paleo', icon: '🍖' },
];

// Cuisine types
export const CUISINE_TYPES = [
    { id: 'any', name: 'Any Cuisine', icon: '🌍' },
    { id: 'Italian', name: 'Italian', icon: '🇮🇹' },
    { id: 'Chinese', name: 'Chinese', icon: '🇨🇳' },
    { id: 'American', name: 'American', icon: '🇺🇸' },
    { id: 'Mexican', name: 'Mexican', icon: '🇲🇽' },
    { id: 'Japanese', name: 'Japanese', icon: '🇯🇵' },
    { id: 'Indian', name: 'Indian', icon: '🇮🇳' },
    { id: 'Thai', name: 'Thai', icon: '🇹🇭' },
    { id: 'Mediterranean', name: 'Mediterranean', icon: '🫒' },
    { id: 'Korean', name: 'Korean', icon: '🇰🇷' },
];